In [1]:
import pandas as pd
import numpy as np
from scipy.stats import kurtosis
from scipy.stats import skew

In [2]:
Q9_a = pd.read_csv('Q9_a.csv')
Q9_a.set_index('Index')

speed  dist
Index             
1          4     2
2          4    10
3          7     4
4          7    22
5          8    16
6          9    10
7         10    18
8         10    26
9         10    34
10        11    17
11        11    28
12        12    14
13        12    20
14        12    24
15        12    28
16        13    26
17        13    34
18        13    34
19        13    46
20        14    26
21        14    36
22        14    60
23        14    80
24        15    20
25        15    26
26        15    54
27        16    32
28        16    40
29        17    32
30        17    40
31        17    50
32        18    42
33        18    56
34        18    76
35        18    84
36        19    36
37        19    46
38        19    68
39        20    32
40        20    48
41        20    52
42        20    56
43        20    64
44        22    66
45        23    54
46        24    70
47        24    92
48        24    93
49        24   120
50        25    85

In [3]:
skew(Q9_a[['speed','dist']])

array([-0.11395477,  0.78248352])

In [4]:
kurtosis(Q9_a[['speed','dist']])

array([-0.57714742,  0.24801866])

In [5]:
Q9_b = pd.read_csv('Q9_b.csv')
Q9_b.rename(columns={'Unnamed: 0':'Index'}, inplace = True)
Q9_b.set_index('Index')

SP         WT
Index                       
1      104.185353  28.762059
2      105.461264  30.466833
3      105.461264  30.193597
4      113.461264  30.632114
5      104.461264  29.889149
...           ...        ...
77     169.598513  16.132947
78     150.576579  37.923113
79     151.598513  15.769625
80     167.944460  39.423099
81     139.840817  34.948615

[81 rows x 2 columns]

In [6]:
skew(Q9_b[['SP','WT']])

array([ 1.58145368, -0.60330993])

In [7]:
kurtosis(Q9_b[['SP','WT']])

array([2.72352149, 0.81946588])